name: Uberjar Build
on: [push, pull_request, release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - uses: extractions/setup-just@v2
      - name: Build Binary
        run: |
          just uberjar

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: jresolve.jar
          path: build/uberjar/jstage-uber.jar